# Generated by Django 4.1.7 on 2023-03-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='dislikeCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='likeCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='markAsSolution',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
