# Generated by Django 4.1.7 on 2023-03-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0005_alter_answers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='dislikeCount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='likeCount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='markAsSolution',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
