# Generated by Django 4.1.7 on 2023-04-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0008_alter_answers_dislikecount_alter_answers_likecount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='docUrl',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
