# Generated by Django 4.1.7 on 2023-04-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0011_question_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologylabel',
            name='labeltitle',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='technologylabel',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
