# Generated by Django 4.1.7 on 2023-04-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0013_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='answer_like',
            new_name='anslike',
        ),
    ]
