# Generated by Django 4.1.7 on 2023-04-19 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask', '0014_rename_answer_like_like_anslike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_badges',
            name='badge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ask.badges'),
        ),
        migrations.AlterField(
            model_name='user_badges',
            name='earnDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_badges',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
