# Generated by Django 4.1.7 on 2023-04-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0015_alter_user_badges_badge_alter_user_badges_earndate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='docUrl',
            new_name='document',
        ),
    ]
