# Generated by Django 4.1.7 on 2023-04-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0016_rename_docurl_answers_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorials',
        ),
    ]
