# Generated by Django 4.1.7 on 2023-04-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0017_delete_tutorials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_badges',
            name='badge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='ask.badges'),
        ),
    ]
