# Generated by Django 4.1.7 on 2023-04-25 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask', '0018_alter_user_badges_badge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='User_Like',
        ),
        migrations.RenameField(
            model_name='user_like',
            old_name='anslike',
            new_name='answer',
        ),
    ]
