# Generated by Django 4.1.7 on 2023-04-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0020_remove_user_like_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologylabel',
            name='label',
            field=models.CharField(max_length=500),
        ),
    ]
