# Generated by Django 4.1.7 on 2023-04-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_gender_alter_user_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
